name: PR Tests

on:
  pull_request:
    branches: ['dev', 'main']
    paths: ['custom_components/tado_hijack/**']

jobs:
  # Job 1: Call the reusable linting workflow.
  lint:
    name: "Run Linter"
    uses: ./.github/workflows/lint.yml

  # Job 2: Call the reusable HACS and hassfest validation workflow.
  validation:
    name: "Run Validation"
    uses: ./.github/workflows/validate.yml
